### PR TITLE
Package Templates

### PR DESCRIPTION
**Pull request by zxawry**
this adds the option to create a package with index files included to feature a full page.
the default template is an image slideshow.

### CODE REVIEW

**Comment by kauffj** [comment]
@zxawry please give us a few more days to address this PR, thank you for your contribution!

**Comment by neb-b** [comment]
Sorry this took so long. Good to go now @zxawry !

**Comment by zxawry** [comment]
No problem, thanks for the merge, you've been busy with the new release I know.
Do you think it's possible to integrate this into the publish page on desktop, so one could choose a directory of images or videos and publish them all at once under one claim in a lbry package?

**Comment by neb-b** [comment]
I think for the time being this will remain a stand alone library, separate from the official lbry app

**Comment by zxawry** [comment]
it's used in the official app for unpacking and sandbox viewer, so I thought it could be reused for packing up as well.

**Comment by tzarebczan** [comment]
@zxawry I did open https://github.com/lbryio/lbry-desktop/issues/2409 but @kauffj (and others) is skeptical of requiring a LBRY specific format to do this packaging/viewing (which is why we want to hold off on more progress here). 

Do you have any ideas on how we can use some existing formats/tools in order to accomplish what we do today with lbry-format?

**Comment by zxawry** [comment]
considering LBRY as a protocol rather than a platform it doesn't seem good to constrain it with specific formats, now I get it.
I'm not an expert on this and can't really tell the difference between .lbry and the normal .tar (apart form the extension names) to guess what it takes to make a package run in a sandbox but I think scanning any archive format for a manifest file or index.html is good enough to tell the app which ones to render as html webviews.

**Pull request merged**
